version: "3.5"
services:
  node-sale-fuse-l2:
    build:
      context: .
      args:
        UPSTREAM_VERSION: 1.0.4
    image: node-sale-fuse-l2.node-sale-fuse-l2.public.dappnode.eth:0.2.1
    environment:
      - NETWORK=
      - PRIVATE_KEY=
      - REWARD_COLLECTOR_ADDRESS=
      - CHECK_NFT_INTERVAL=
      - COMISSION_RATE=
      - EXTRA_OPTS=
    ports:
      - 37000:37000/tcp
      - 37000:37000/udp
      - 37001:37001/tcp
      - 37001:37001/udp
      - 7007:7007/tcp
      - 9944:9944/tcp
    volumes:
      - avail-node_data:/data
    restart: unless-stopped
volumes:
  avail-node_data: {}
